### ISSUE TITLE
How to obtain the landmark images and parsing images?

### ISSUE THREAD

**Issue by csyxwei** [liqi-casia/FaceSwapper#1]
Hi, thanks for your great work!

I want to use the pretrained model to test our customed images,  could you tell how to obtain the landmark images and parsing images?

**Comment by liqi-casia** [comment]
Sorry for the delay. 
1. I have added [_get_landmark_curve_](https://github.com/liqi-casia/FaceSwapper/blob/e5db44af5fa7027f12cb728c37047f4cc89bc201/core/wing.py#L440) function to generate the landmark images. Suppose that the input is _x_ , you can simply write the code as follows:
`lm_images = fan.get_landmark_curve(x)`
`lm_images = torch.from_numpy(np.array(lm_images).transpose(0, 3, 1, 2)).type(dtype=torch.float)`
`lm_images  = lm_images.to(x.device) / 255`.
And then employ `utils.save_image` to save these images one by one.
2.  We use this project to generate the parsing images [face parsing: BiSeNet](https://github.com/zllrunning/face-parsing.PyTorch). You can refer this project for the details.

>

**Comment by csyxwei** [comment]
Thanks a lot!

**Comment by loboere** [comment]
could explain better what is "x" how to load?  .
I also think you have syntax errors in.  

@torch.no_grad()   no aligned
input = x[i] r        r is undefined


this is correct
```
    @torch.no_grad()
    def get_landmark_curve(self, x):  
        heatmaps = self.get_heatmap(x, b_preprocess=False)
        landmarks = []
        for i in range(x.size(0)):
            pred_landmarks = get_preds_fromhm(heatmaps[i].cpu().unsqueeze(0))
            landmarks.append(pred_landmarks)
        scale_factor = x.size(2) // heatmaps.size(2)
        landmarks = torch.cat(landmarks) * scale_factor
        batch_landmark_figure =[]
        for i in range(0,len(x)):
            dpi = 100
            input = x[i]
```
