### ISSUE TITLE
how test custom images

### ISSUE THREAD

**Issue by loboere** [liqi-casia/FaceSwapper#3]
how get (lm , mask , parsing ) images?

**Comment by liqi-casia** [comment]
Please refer to  https://github.com/liqi-casia/FaceSwapper/issues/1#issuecomment-1085592984

**Comment by loboere** [comment]
could explain better what is "x" how to load?  .
I also think you have syntax errors in.  

@torch.no_grad()   no aligned
input = x[i] r        r is undefined


this is correct
```
    @torch.no_grad()
    def get_landmark_curve(self, x):  
        heatmaps = self.get_heatmap(x, b_preprocess=False)
        landmarks = []
        for i in range(x.size(0)):
            pred_landmarks = get_preds_fromhm(heatmaps[i].cpu().unsqueeze(0))
            landmarks.append(pred_landmarks)
        scale_factor = x.size(2) // heatmaps.size(2)
        landmarks = torch.cat(landmarks) * scale_factor
        batch_landmark_figure =[]
        for i in range(0,len(x)):
            dpi = 100
            input = x[i]
```

**Comment by liqi-casia** [comment]
> could explain better what is "x" how to load? . I also think you have syntax errors in.
> 
> @torch.no_grad() no aligned input = x[i] r r is undefined
> 
> this is correct
> 
> ```
>     @torch.no_grad()
>     def get_landmark_curve(self, x):  
>         heatmaps = self.get_heatmap(x, b_preprocess=False)
>         landmarks = []
>         for i in range(x.size(0)):
>             pred_landmarks = get_preds_fromhm(heatmaps[i].cpu().unsqueeze(0))
>             landmarks.append(pred_landmarks)
>         scale_factor = x.size(2) // heatmaps.size(2)
>         landmarks = torch.cat(landmarks) * scale_factor
>         batch_landmark_figure =[]
>         for i in range(0,len(x)):
>             dpi = 100
>             input = x[i]
> ```

1.  x is the input (a batch of images).
2. I have corrected the _get_landmark_curve_. There should be no **r** in the function.

**Comment by loboere** [comment]
give me the code to load images try this but it does not work.

```
from core.wing import FAN
import cv2
import numpy as np
 

fan= FAN()
img=np.array(cv2.imread("/content/data2/1.jpg")) 
lm_images = fan.get_landmark_curve( img )
lm_images = torch.from_numpy(np.array(lm_images).transpose(0, 3, 1, 2)).type(dtype=torch.float)
lm_images = lm_images.to(x.device) / 255.


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-36-9d3db08dc8bb>](https://localhost:8080/#) in <module>()
      6 fan= FAN()
      7 img=np.array(cv2.imread("/content/data2/1.jpg"))
----> 8 lm_images = fan.get_landmark_curve( img )
      9 lm_images = torch.from_numpy(np.array(lm_images).transpose(0, 3, 1, 2)).type(dtype=torch.float)
     10 lm_images = lm_images.to(x.device) / 255.

4 frames
[/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in interpolate(input, size, scale_factor, mode, align_corners, recompute_scale_factor)
   3637             align_corners = False
   3638 
-> 3639     dim = input.dim() - 2  # Number of spatial dimensions.
   3640 
   3641     # Process size and scale_factor.  Validate that exactly one is set.

AttributeError: 'numpy.ndarray' object has no attribute 'dim'
```

**Comment by liqi-casia** [comment]
The batch of images should be in GPU mode. You can utilize the _data_loader.py_  to load images and then send these images to _get_landmark_curve_ function.

**Comment by liqi-casia** [comment]
You can also refer to this issue 

> https://github.com/liqi-casia/FaceSwapper/issues/5#issue-1201935426
