### ISSUE TITLE
Any plans to make a full working demo like in SimSwap, sber-swap and others?

### ISSUE THREAD

**Issue by netrunner-exe** [liqi-casia/FaceSwapper#4]
Good afternoon. Any plans to make a full working demo like in SimSwap, sber-swap and others, maybe Colab? I think in this case this project would attract much more attention of users.

**Comment by liqi-casia** [comment]
Thanks for your interest in this project. I am a little busy now, so a full working demo may be postponed.  If possible, you can refer these projects to make a full demo.
